[package]
name = "niri-scratchpad"
version = "0.9.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
niri-ipc = "25.8.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
